// Mocks generated by Mockito 5.4.2 from annotations
// in storebill_pro_plus/test/ai_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:storebill_pro_plus/services/ai_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AIService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAIService extends _i1.Mock implements _i2.AIService {
  MockAIService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String> suggestDescription(
    String? productName,
    String? category,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #suggestDescription,
          [
            productName,
            category,
          ],
        ),
        returnValue: _i3.Future<String>.value(''),
      ) as _i3.Future<String>);
  @override
  _i3.Future<String> getDashboardInsight(
    double? sales,
    double? purchases,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDashboardInsight,
          [
            sales,
            purchases,
          ],
        ),
        returnValue: _i3.Future<String>.value(''),
      ) as _i3.Future<String>);
}
