// Mocks generated by Mockito 5.4.4 from annotations
// in storebill_pro_plus/test/pdf_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;
import 'package:storebill_pro_plus/providers/store_provider.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [StoreProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockStoreProvider extends _i1.Mock implements _i2.StoreProvider {
  MockStoreProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get storeName => (super.noSuchMethod(
        Invocation.getter(#storeName),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#storeName),
        ),
      ) as String);

  @override
  String get storeAddress => (super.noSuchMethod(
        Invocation.getter(#storeAddress),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#storeAddress),
        ),
      ) as String);

  @override
  String get storeTerms => (super.noSuchMethod(
        Invocation.getter(#storeTerms),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#storeTerms),
        ),
      ) as String);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> setStoreName(String? name) => (super.noSuchMethod(
        Invocation.method(
          #setStoreName,
          [name],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setStoreIcon(String? path) => (super.noSuchMethod(
        Invocation.method(
          #setStoreIcon,
          [path],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setStoreAddress(String? address) => (super.noSuchMethod(
        Invocation.method(
          #setStoreAddress,
          [address],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setStoreTerms(String? terms) => (super.noSuchMethod(
        Invocation.method(
          #setStoreTerms,
          [terms],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void addListener(_i5.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i5.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
