// Mocks generated by Mockito 5.4.4 from annotations
// in storebill_pro_plus/test/product_form_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:ui' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:storebill_pro_plus/models/product_model.dart' as _i3;
import 'package:storebill_pro_plus/providers/product_provider.dart' as _i2;
import 'package:storebill_pro_plus/services/ai_service.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ProductProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductProvider extends _i1.Mock implements _i2.ProductProvider {
  MockProductProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i3.Product> get products => (super.noSuchMethod(
        Invocation.getter(#products),
        returnValue: <_i3.Product>[],
      ) as List<_i3.Product>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void addProduct({
    required String? name,
    required String? category,
    required double? purchasePrice,
    required double? salePrice,
    required int? stockQty,
    required String? unit,
    String? description,
    String? barcode,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #addProduct,
          [],
          {
            #name: name,
            #category: category,
            #purchasePrice: purchasePrice,
            #salePrice: salePrice,
            #stockQty: stockQty,
            #unit: unit,
            #description: description,
            #barcode: barcode,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateProduct(_i3.Product? product) => super.noSuchMethod(
        Invocation.method(
          #updateProduct,
          [product],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void deleteProduct(String? id) => super.noSuchMethod(
        Invocation.method(
          #deleteProduct,
          [id],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Product? getProductById(String? id) =>
      (super.noSuchMethod(Invocation.method(
        #getProductById,
        [id],
      )) as _i3.Product?);

  @override
  void updateStock(
    String? productId,
    int? quantityChange,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #updateStock,
          [
            productId,
            quantityChange,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i4.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i4.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [AIService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAIService extends _i1.Mock implements _i5.AIService {
  MockAIService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<String> suggestDescription(
    String? productName,
    String? category,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #suggestDescription,
          [
            productName,
            category,
          ],
        ),
        returnValue: _i6.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #suggestDescription,
            [
              productName,
              category,
            ],
          ),
        )),
      ) as _i6.Future<String>);

  @override
  _i6.Future<String> getDashboardInsight(
    double? sales,
    double? purchases,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDashboardInsight,
          [
            sales,
            purchases,
          ],
        ),
        returnValue: _i6.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #getDashboardInsight,
            [
              sales,
              purchases,
            ],
          ),
        )),
      ) as _i6.Future<String>);
}
