// Mocks generated by Mockito 5.4.2 from annotations
// in storebill_pro_plus/test/sales_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i3;

import 'package:hive/hive.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:storebill_pro_plus/models/customer_model.dart' as _i8;
import 'package:storebill_pro_plus/models/product_model.dart' as _i7;
import 'package:storebill_pro_plus/providers/customer_provider.dart' as _i6;
import 'package:storebill_pro_plus/providers/product_provider.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBox_0<E> extends _i1.SmartFake implements _i2.Box<E> {
  _FakeBox_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLazyBox_1<E> extends _i1.SmartFake implements _i2.LazyBox<E> {
  _FakeLazyBox_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [Box].
///
/// See the documentation for Mockito's code generation for more information.
class MockBox<E> extends _i1.Mock implements _i2.Box<E> {
  MockBox() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Iterable<E> get values => (super.noSuchMethod(
        Invocation.getter(#values),
        returnValue: [],
      ) as Iterable<E>);
  @override
  String get name => (super.noSuchMethod(
        Invocation.getter(#name),
        returnValue: '',
      ) as String);
  @override
  bool get isOpen => (super.noSuchMethod(
        Invocation.getter(#isOpen),
        returnValue: false,
      ) as bool);
  @override
  bool get lazy => (super.noSuchMethod(
        Invocation.getter(#lazy),
        returnValue: false,
      ) as bool);
  @override
  Iterable<dynamic> get keys => (super.noSuchMethod(
        Invocation.getter(#keys),
        returnValue: [],
      ) as Iterable<dynamic>);
  @override
  int get length => (super.noSuchMethod(
        Invocation.getter(#length),
        returnValue: 0,
      ) as int);
  @override
  bool get isEmpty => (super.noSuchMethod(
        Invocation.getter(#isEmpty),
        returnValue: false,
      ) as bool);
  @override
  bool get isNotEmpty => (super.noSuchMethod(
        Invocation.getter(#isNotEmpty),
        returnValue: false,
      ) as bool);
  @override
  _i2.Box<E> get box => (super.noSuchMethod(
        Invocation.getter(#box),
        returnValue: _FakeBox_0<E>(
          this,
          Invocation.getter(#box),
        ),
      ) as _i2.Box<E>);
  @override
  _i2.LazyBox<E> get lazyBox => (super.noSuchMethod(
        Invocation.getter(#lazyBox),
        returnValue: _FakeLazyBox_1<E>(
          this,
          Invocation.getter(#lazyBox),
        ),
      ) as _i2.LazyBox<E>);
  @override
  E? get(
    dynamic key, {
    E? defaultValue,
  }) =>
      (super.noSuchMethod(Invocation.method(
        #get,
        [key],
        {#defaultValue: defaultValue},
      )) as E?);
  @override
  E? getAt(int? index) => (super.noSuchMethod(Invocation.method(
        #getAt,
        [index],
      )) as E?);
  @override
  _i4.Future<void> put(
    dynamic key,
    E? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [
            key,
            value,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> putAt(
    int? index,
    E? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #putAt,
          [
            index,
            value,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> delete(dynamic key) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [key],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> deleteAt(int? index) => (super.noSuchMethod(
        Invocation.method(
          #deleteAt,
          [index],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<int> add(E? value) => (super.noSuchMethod(
        Invocation.method(
          #add,
          [value],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);
  @override
  _i4.Future<Iterable<int>> addAll(Iterable<E>? values) => (super.noSuchMethod(
        Invocation.method(
          #addAll,
          [values],
        ),
        returnValue: _i4.Future<Iterable<int>>.value([]),
      ) as _i4.Future<Iterable<int>>);
  @override
  _i4.Future<void> putAll(Map<dynamic, E>? entries) => (super.noSuchMethod(
        Invocation.method(
          #putAll,
          [entries],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<int> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);
  @override
  _i4.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> compact() => (super.noSuchMethod(
        Invocation.method(
          #compact,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  bool containsKey(dynamic key) => (super.noSuchMethod(
        Invocation.method(
          #containsKey,
          [key],
        ),
        returnValue: false,
      ) as bool);
  @override
  _i4.Stream<_i2.BoxEvent> watch({dynamic key}) => (super.noSuchMethod(
        Invocation.method(
          #watch,
          [],
          {#key: key},
        ),
        returnValue: _i4.Stream<_i2.BoxEvent>.empty(),
      ) as _i4.Stream<_i2.BoxEvent>);
  @override
  Map<dynamic, E> toMap() => (super.noSuchMethod(
        Invocation.method(
          #toMap,
          [],
        ),
        returnValue: <dynamic, E>{},
      ) as Map<dynamic, E>);
  @override
  _i4.Future<void> deleteAll(Iterable<dynamic>? keys) => (super.noSuchMethod(
        Invocation.method(
          #deleteAll,
          [keys],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> flush() => (super.noSuchMethod(
        Invocation.method(
          #flush,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [ProductProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductProvider extends _i1.Mock implements _i5.ProductProvider {
  MockProductProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i7.Product> get products => (super.noSuchMethod(
        Invocation.getter(#products),
        returnValue: <_i7.Product>[],
      ) as List<_i7.Product>);
  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);
  @override
  void addProduct({
    required String? name,
    required String? category,
    required double? purchasePrice,
    required double? salePrice,
    required int? stockQty,
    required String? unit,
    String? description,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #addProduct,
          [],
          {
            #name: name,
            #category: category,
            #purchasePrice: purchasePrice,
            #salePrice: salePrice,
            #stockQty: stockQty,
            #unit: unit,
            #description: description,
          },
        ),
        returnValueForMissingStub: null,
      );
  @override
  void updateProduct(_i7.Product? product) => super.noSuchMethod(
        Invocation.method(
          #updateProduct,
          [product],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void deleteProduct(String? id) => super.noSuchMethod(
        Invocation.method(
          #deleteProduct,
          [id],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i7.Product? getProductById(String? id) =>
      (super.noSuchMethod(Invocation.method(
        #getProductById,
        [id],
      )) as _i7.Product?);
  @override
  void updateStock(
    String? productId,
    int? quantityChange,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #updateStock,
          [
            productId,
            quantityChange,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void addListener(_i3.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void removeListener(_i3.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [CustomerProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockCustomerProvider extends _i1.Mock implements _i6.CustomerProvider {
  MockCustomerProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i8.Customer> get customers => (super.noSuchMethod(
        Invocation.getter(#customers),
        returnValue: <_i8.Customer>[],
      ) as List<_i8.Customer>);
  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);
  @override
  void addCustomer({
    required String? name,
    String? phoneNumber,
    String? email,
    double? totalDue,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #addCustomer,
          [],
          {
            #name: name,
            #phoneNumber: phoneNumber,
            #email: email,
            #totalDue: totalDue,
          },
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i8.Customer? getCustomerByName(String? name) =>
      (super.noSuchMethod(Invocation.method(
        #getCustomerByName,
        [name],
      )) as _i8.Customer?);
  @override
  void updateCustomerDue(
    String? customerName,
    double? amount,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #updateCustomerDue,
          [
            customerName,
            amount,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void markPaymentReceived(
    String? customerId,
    double? amount,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #markPaymentReceived,
          [
            customerId,
            amount,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void addListener(_i3.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void removeListener(_i3.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
